language: cpp

matrix:

  include:
    - env: ELECTRONPASS_PLATFORM='windows32'
      os: linux
      dist: trusty
      sudo: required
      compiler: gcc

    - env: ELECTRONPASS_PLATFORM='windows64'
      os: linux
      dist: trusty
      sudo: required
      compiler: gcc

    - env: ELECTRONPASS_PLATFORM='macXX'
      os: osx
      osx_image: xcode7.2
      compiler: clang

before_install:
  - ELECTRONPASS_TARGET="${ELECTRONPASS_PLATFORM::${#ELECTRONPASS_PLATFORM}-2}"
  - ./build/${ELECTRONPASS_TARGET}/requirements.sh

install:
  - source ./build/${ELECTRONPASS_TARGET}/build.sh

script:
  - echo "Nothing."

before_deploy:
  - # source build-dir/package.sh
